name: CrowdSeq-Client release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.20.1

      - name: Install dependencies
        run: npm install

      - name: Build the package
        run: npm run build

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.20.1

      - name: Install dependencies
        run: npm install

      - name: Generate release notes and changelog
        env:
          GH_TOKEN: ${{ secrets.GH1_TOKEN }}
        run: npx semantic-release

      - name: Get Latest Tag
        id: latest_tag
        run: |
          echo "TAG=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: davelabhub/crowdseq-client:${{ env.TAG }}, davelabhub/crowdseq-client:latest
